### ISSUE TITLE
when running ./install-kubeflow.sh, getting internal error message.

### ISSUE THREAD

**Issue by gpitchai** [oracle-devrel/kubeflow-oke#11]
Error from server (InternalError): error when creating "STDIN": Internal error occurred: failed calling webhook "clusterservingruntime.kserve-webhook-server.validator": failed to call webhook: Post "https://kserve-webhook-server-service.kubeflow.svc:443/validate-serving-kserve-io-v1alpha1-clusterservingruntime?timeout=10s": no endpoints available for service "kserve-webhook-server-service"
Error from server (InternalError): error when creating "STDIN": Internal error occurred: failed calling webhook "clusterservingruntime.kserve-webhook-server.validator": failed to call webhook: Post "https://kserve-webhook-server-service.kubeflow.svc:443/validate-serving-kserve-io-v1alpha1-clusterservingruntime?timeout=10s": no endpoints available for service "kserve-webhook-server-service"
Error from server (InternalError): error when creating "STDIN": Internal error occurred: failed calling webhook "clusterservingruntime.kserve-webhook-server.validator": failed to call webhook: Post "https://kserve-webhook-server-service.kubeflow.svc:443/validate-serving-kserve-io-v1alpha1-clusterservingruntime?timeout=10s": no endpoints available for service "kserve-webhook-server-service"
Error from server (InternalError): error when creating "STDIN": Internal error occurred: failed calling webhook "clusterservingruntime.kserve-webhook-server.validator": failed to call webhook: Post "https://kserve-webhook-server-service.kubeflow.svc:443/validate-serving-kserve-io-v1alpha1-clusterservingruntime?timeout=10s": no endpoints available for service "kserve-webhook-server-service"
Error from server (InternalError): error when creating "STDIN": Internal error occurred: failed calling webhook "clusterservingruntime.kserve-webhook-server.validator": failed to call webhook: Post "https://kserve-webhook-server-service.kubeflow.svc:443/validate-serving-kserve-io-v1alpha1-clusterservingruntime?timeout=10s": no endpoints available for service "kserve-webhook-server-service"
Error from server (InternalError): error when creating "STDIN": Internal error occurred: failed calling webhook "clusterservingruntime.kserve-webhook-server.validator": failed to call webhook: Post "https://kserve-webhook-server-service.kubeflow.svc:443/validate-serving-kserve-io-v1alpha1-clusterservingruntime?timeout=10s": no endpoints available for service "kserve-webhook-server-service"
Error from server (InternalError): error when creating "STDIN": Internal error occurred: failed calling webhook "clusterservingruntime.kserve-webhook-server.validator": failed to call webhook: Post "https://kserve-webhook-server-service.kubeflow.svc:443/validate-serving-kserve-io-v1alpha1-clusterservingruntime?timeout=10s": no endpoints available for service "kserve-webhook-server-service"
Error from server (InternalError): error when creating "STDIN": Internal error occurred: failed calling webhook "clusterservingruntime.kserve-webhook-server.validator": failed to call webhook: Post "https://kserve-webhook-server-service.kubeflow.svc:443/validate-serving-kserve-io-v1alpha1-clusterservingruntime?timeout=10s": no endpoints available for service "kserve-webhook-server-service"
Error from server (InternalError): error when creating "STDIN": Internal error occurred: failed calling webhook "clusterservingruntime.kserve-webhook-server.validator": failed to call webhook: Post "https://kserve-webhook-server-service.kubeflow.svc:443/validate-serving-kserve-io-v1alpha1-clusterservingruntime?timeout=10s": no endpoints available for service "kserve-webhook-server-service"
Retrying to apply resources

**Comment by julioo** [comment]
@gpitchai did you create the OKE cluster with the terraform script provided, with the terraform provided cloud-init is applied. Please confirm OKE the version >= v1.27.2

**Comment by gpitchai** [comment]
@julioo Yes, OKE was provided using TF script and the OKE version is 1.27.2

**Comment by julioo** [comment]
@gpitchai How many nodes and OCPU did you deploy ? Make sure to have enough resources
Confirm containers status:
`kubectl get po -A`

**Comment by gpitchai** [comment]
@julioo currently I am running 7 OCPUS and 7 nodes. Following services are up and running.
NAMESPACE     NAME                                   READY   STATUS    RESTARTS        AGE
kube-system   coredns-7498987c54-548vh               1/1     Running   0               4d23h
kube-system   coredns-7498987c54-5gbv9               1/1     Running   0               4d23h
kube-system   coredns-7498987c54-8nhrg               1/1     Running   0               4d23h
kube-system   coredns-7498987c54-dbcnm               1/1     Running   0               4d23h
kube-system   coredns-7498987c54-lr6xh               1/1     Running   0               4d23h
kube-system   coredns-7498987c54-nffkb               1/1     Running   0               4d23h
kube-system   coredns-7498987c54-trcm4               1/1     Running   0               4d23h
kube-system   csi-oci-node-565zg                     1/1     Running   1 (4d23h ago)   4d23h
kube-system   csi-oci-node-gdgwz                     1/1     Running   0               4d23h
kube-system   csi-oci-node-hgnbb                     1/1     Running   0               4d23h
kube-system   csi-oci-node-mvwnb                     1/1     Running   0               4d23h
kube-system   csi-oci-node-pdgvp                     1/1     Running   0               4d23h
kube-system   csi-oci-node-xgdrq                     1/1     Running   0               4d23h
kube-system   csi-oci-node-z2lft                     1/1     Running   0               4d23h
kube-system   kube-dns-autoscaler-589f67587d-bsfqq   1/1     Running   2 (4h14m ago)   4d23h
kube-system   kube-flannel-ds-6vhgf                  1/1     Running   1 (4d23h ago)   4d23h
kube-system   kube-flannel-ds-8psv8                  1/1     Running   1 (4d23h ago)   4d23h
kube-system   kube-flannel-ds-ht4fz                  1/1     Running   1 (4d23h ago)   4d23h
kube-system   kube-flannel-ds-mwmpk                  1/1     Running   1 (4d23h ago)   4d23h
kube-system   kube-flannel-ds-n96s7                  1/1     Running   1 (4d23h ago)   4d23h
kube-system   kube-flannel-ds-prr9r                  1/1     Running   1 (4d23h ago)   4d23h
kube-system   kube-flannel-ds-r2nr8                  1/1     Running   1 (4d23h ago)   4d23h
kube-system   kube-proxy-8bkqc                       1/1     Running   0               4d23h
kube-system   kube-proxy-8wqtq                       1/1     Running   0               4d23h
kube-system   kube-proxy-fxbwd                       1/1     Running   0               4d23h
kube-system   kube-proxy-mjwtc                       1/1     Running   0               4d23h
kube-system   kube-proxy-qwnk7                       1/1     Running   0               4d23h
kube-system   kube-proxy-ssghc                       1/1     Running   0               4d23h
kube-system   kube-proxy-xkwdv                       1/1     Running   0               4d23h
kube-system   proxymux-client-55787                  1/1     Running   0               4d23h
kube-system   proxymux-client-cp5ql                  1/1     Running   0               4d23h
kube-system   proxymux-client-db22d                  1/1     Running   0               4d23h
kube-system   proxymux-client-hw8gh                  1/1     Running   0               4d23h
kube-system   proxymux-client-n6gpd                  1/1     Running   0               4d23h
kube-system   proxymux-client-qp4nr                  1/1     Running   0               4d23h
kube-system   proxymux-client-s7ctb                  1/1     Running   0               4d23h

**Comment by julioo** [comment]
@gpitchai please show all the namespaces, the following command
`kubectl get po -A`

**Comment by gpitchai** [comment]
@julioo Output that I shared in my previous comment was the output of Kubectl get po -A.
kubectl get ns
NAME              STATUS   AGE
default           Active   5d
kube-node-lease   Active   5d
kube-public       Active   5d
kube-system       Active   5d

**Comment by julioo** [comment]
@gpitchai can you confirm kustomize version ?

**Comment by julioo** [comment]
@gpitchai After further testing, we found that disabling OKE in-transit encryption may resolve the issue. Your input before closing the matter would be appreciated.

**Comment by julioo** [comment]
Closing make sure to disable OKE in-transit encryption
